# CREATE A FUNCTION WHICH WILL BE ASK ENDPOINT WITH WEBSITE CONTAINING EXCHANGE RATES

# ADD EXCEPTIONS TRY: & EXCEPT

# ADD SECOND FUNCTIONS WHICH WILL BE MEASURING TIME OF DURATION AND TIME + DATE WHEN THE REQUEST HAPPEND

# RETURN THIS REQUEST IN PRINT

# WHOLE PROGRAMM SHOULD BE DONE IN A LOOP IN INTERVAL OF 15 MINUTES

# IN ADDITION GENERETE THE CSV REPORT